### ISSUE TITLE
[BUG]: Ingress nodes do not upgrade to https when using http

### ISSUE THREAD

**Issue by chris-dickson** [DARPA-ASKEM/orchestration#50]
Going to http://xxxx.staging.terarium.ai "works" but the browser shows a cert warning.  Using http for any of our services should automatically forward to https.

**Comment by bigglesandginger** [comment]
This needs the AWS load-balancer to not forward _both_ 80 and 443 to 8078.  80 Needs to forward to a different port, then we can add a VirtualHost for that port to perform the HSTS stuff

**Comment by dgauldie** [comment]
this now redirects
