### ISSUE TITLE
[TASK]: Need neo4j , es, minio to be part of ghrc packages

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/orchestration#51]
neo4j: 5.x
minio: latest 
es: 8
postgres: 15

**Comment by bigglesandginger** [comment]
ghcr.io/darpa-askem/neo4j:5.3.0 copied
ghcr.io/darpa-askem/postgres:15.1 copied
ghcr.io/darpa-askem/elasticsearch:8.5.3 copied
ghcr.io/darpa-askem/minio:RELEASE.2022-12-12T19-27-27Z copied

**Comment by bigglesandginger** [comment]
Copied images using regctl (https://github.com/regclient/regclient/releases) using the following command: regctl image copy <source_image:tag> <target_image:tag>

**Comment by Nithos** [comment]
Discussed with Yohann, but putting it here for future reference. Re-tagging and pushing images to this space will require manual changes to allow all team members to access them. By default it is private to the account that pushed the package up (unless its tied to a repo that inherits the access list). So just caution to make sure that new packages are tested and accessible to all.

**Comment by bigglesandginger** [comment]
How ?

**Comment by Nithos** [comment]
One needs to go to the package, then package settings then add the appropriate Team Members. I believe Yohann is making a new group for this to make it easier.

**Comment by YohannParis** [comment]
I did create an _ASKEM_ team that all other teams are children of.
that group has been given *read* access to all packages.
